apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.coordinating.fullname" . }}-headless
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinating-only
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 9200
      targetPort: http
    - name: tcp-transport
      port: 9300
      targetPort: transport
  selector: {{- include "elasticsearch.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinating-only
