apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.data.fullname" . }}-headless
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-transport
      port: 9300
      targetPort: transport
  selector: {{- include "elasticsearch.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: data
